//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCrud1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int AlumnoId { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> DNI { get; set; }
        public string NombreApoderado { get; set; }
        public Nullable<int> Telefono { get; set; }
        public Nullable<int> Celular { get; set; }
    }
}
